name: CI

on:
  push:
    branches: [test-actions]
  pull_request:
    branches: [main]

jobs:
  build-publishable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm i -g npm@9
      - run: npm ci

      - name: Build the publishable packages
        run: npx nx run-many --target=build --exclude=docs,@rjsf/playground
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: publishable-build-results
          path: packages/*/dist
  tests:
    runs-on: ubuntu-latest
    needs: [build-publishable]
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm i -g npm@9
      - run: npm ci
      - run: npm run lint
      - run: npm run cs-check
      - name: Download build results
        uses: actions/download-artifact@v3
        with:
          name: publishable-build-results
          path: packages
      - run: npm test
  build-docs:
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm i -g npm@9
      - run: npm ci

      - name: Build docs
        run: npm run build
        working-directory: packages/docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Build docs
        run: npm run build
        working-directory: packages/playground
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - if: matrix.node-version == '18.x'
        uses: actions/upload-artifact@v3
        with:
          name: playground
          path: packages/playground/dist
      - if: matrix.node-version == '18.x'
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: packages/docs/build
      - run: npm test
  deploy_playground_and_docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy playground and docs to GitHub Pages
    needs: [build-docs]
    steps:
      - name: Download built playground
        uses: actions/download-artifact@v3
        with:
          name: playground
          path: dist
      - name: Download built docs
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: dist/docs
      - name: Deploy playground + docs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          keep_history: true
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
